'use strict';

// OpenVibe Ecosystem Registry
// Single source of truth for all domains, services, capabilities, and metadata.
// Category values: kernel | foundation | core_product | creator_economy | discovery_growth

const ECOSYSTEM_SERVICES = Object.freeze([
    // ── Kernel ────────────────────────────────────────────────────────────────
    {
        id: 'openvibe-network',
        domain: 'auth.openvibe.network',
        label: 'OpenVibe Auth & Network',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-network',
        publicOrigin: 'https://auth.openvibe.network',
        internalOrigin: 'http://localhost:4100',
        authRequired: false,
        capabilities: ['auth.sso', 'auth.jwks', 'my.account', 'themes.sync'],
        eventTopics: ['auth.events', 'user.events', 'service.events'],
        dependsOn: [],
        provides: ['jwt_validation', 'sso', 'user_identity', 'theme_preferences'],
    },
    {
        id: 'openvibe-api',
        domain: 'api.openvibe.network',
        label: 'OpenVibe API Gateway',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-api',
        publicOrigin: 'https://api.openvibe.network',
        internalOrigin: 'http://localhost:4200',
        authRequired: false,
        capabilities: ['api.gateway', 'api.keys'],
        eventTopics: [],
        dependsOn: ['openvibe-network'],
        provides: ['api_gateway', 'service_discovery', 'api_keys'],
    },
    {
        id: 'openvibe-control',
        domain: 'admin.openvibe.network',
        label: 'OpenVibe Admin Control',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-control',
        publicOrigin: 'https://admin.openvibe.network',
        internalOrigin: 'http://localhost:4300',
        authRequired: true,
        capabilities: ['admin.control'],
        eventTopics: ['service.events'],
        dependsOn: ['openvibe-network', 'openvibe-events', 'openvibe-api'],
        provides: ['admin_dashboard', 'service_control', 'event_replay', 'migration_control'],
    },
    {
        id: 'openvibe-events',
        domain: 'events.openvibe.network',
        label: 'OpenVibe Events',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-events',
        publicOrigin: 'https://events.openvibe.network',
        internalOrigin: 'http://localhost:4400',
        authRequired: false,
        capabilities: ['events.publish', 'events.subscribe', 'events.replay'],
        eventTopics: ['system.events'],
        dependsOn: ['openvibe-network'],
        provides: ['event_bus', 'event_replay', 'event_history'],
    },
    {
        id: 'openvibe-billing',
        domain: 'billing.openvibe.network',
        label: 'OpenVibe Billing',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-billing',
        publicOrigin: 'https://billing.openvibe.network',
        internalOrigin: 'http://localhost:5001',
        authRequired: true,
        capabilities: ['billing.tips', 'billing.vip'],
        eventTopics: ['billing.events', 'tips.events', 'vip.events'],
        dependsOn: ['openvibe-network'],
        provides: ['tips', 'vip_subscriptions', 'wallet', 'credits'],
    },
    {
        id: 'openvibe-ai',
        domain: 'ai.openvibe.network',
        label: 'OpenVibe AI',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-ai',
        publicOrigin: 'https://ai.openvibe.network',
        internalOrigin: 'http://localhost:5100',
        authRequired: true,
        capabilities: ['ai.transcription', 'ai.summarization'],
        eventTopics: ['ai.events'],
        dependsOn: ['openvibe-network', 'openvibe-media'],
        provides: ['transcription', 'summarization', 'ai_routing'],
    },
    {
        id: 'openvibe-realtime',
        domain: 'realtime.openvibe.network',
        label: 'OpenVibe Realtime',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-realtime',
        publicOrigin: 'wss://realtime.openvibe.network',
        internalOrigin: 'http://localhost:5400',
        authRequired: false,
        capabilities: ['realtime.subscribe', 'realtime.presence'],
        eventTopics: [],
        dependsOn: ['openvibe-events'],
        provides: ['websocket_realtime', 'sse_realtime', 'presence'],
    },
    {
        id: 'openvibe-network-my',
        domain: 'my.openvibe.network',
        label: 'My OpenVibe Account',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-network',
        publicOrigin: 'https://my.openvibe.network',
        internalOrigin: 'http://localhost:4100',
        authRequired: true,
        capabilities: ['my.account'],
        eventTopics: ['user.events'],
        dependsOn: ['openvibe-network'],
        provides: ['account_dashboard', 'profile', 'settings'],
    },
    {
        id: 'openvibe-network-themes',
        domain: 'themes.openvibe.network',
        label: 'OpenVibe Themes',
        category: 'kernel',
        status: 'current',
        repoSurface: 'services/openvibe-network',
        publicOrigin: 'https://themes.openvibe.network',
        internalOrigin: 'http://localhost:4100',
        authRequired: false,
        capabilities: ['themes.sync'],
        eventTopics: ['user.events'],
        dependsOn: ['openvibe-network'],
        provides: ['theme_sync', 'css_variables', 'theme_catalog'],
    },

    // ── Foundations ───────────────────────────────────────────────────────────
    {
        id: 'openvibe-media',
        domain: 'openvibe.media',
        label: 'OpenVibe Media',
        category: 'foundation',
        status: 'current',
        repoSurface: 'services/openvibe-media',
        publicOrigin: 'https://openvibe.media',
        internalOrigin: 'http://localhost:4500',
        authRequired: false,
        capabilities: ['media.upload', 'media.vod', 'media.clip'],
        eventTopics: ['media.events'],
        dependsOn: ['openvibe-network'],
        provides: ['media_upload', 'vod_storage', 'clip_storage', 'thumbnails'],
    },
    {
        id: 'openvibe-sdk',
        domain: null,
        label: 'OpenVibe SDK',
        category: 'foundation',
        status: 'current',
        repoSurface: 'packages/openvibe-sdk',
        publicOrigin: null,
        internalOrigin: null,
        authRequired: false,
        capabilities: ['realtime.subscribe'],
        eventTopics: [],
        dependsOn: ['openvibe-realtime'],
        provides: ['realtime_client', 'auth_client', 'service_clients', 'url_defaults'],
    },
    {
        id: 'openvibe-contracts',
        domain: null,
        label: 'OpenVibe Contracts',
        category: 'foundation',
        status: 'current',
        repoSurface: 'packages/openvibe-contracts',
        publicOrigin: null,
        internalOrigin: null,
        authRequired: false,
        capabilities: [],
        eventTopics: [],
        dependsOn: [],
        provides: ['event_contracts', 'capability_catalog', 'ecosystem_registry', 'topic_definitions'],
    },

    // ── Core Product Surfaces ─────────────────────────────────────────────────
    {
        id: 'openvibe-live',
        domain: 'openvibe.live',
        label: 'OpenVibe Live',
        category: 'core_product',
        status: 'current',
        repoSurface: 'services/openvibe-live',
        publicOrigin: 'https://openvibe.live',
        internalOrigin: 'http://localhost:4600',
        authRequired: false,
        capabilities: ['stream.ingest', 'stream.restream', 'realtime.subscribe'],
        eventTopics: ['stream.events', 'media.events'],
        dependsOn: ['openvibe-network', 'openvibe-realtime', 'openvibe-media', 'openre-stream'],
        provides: ['live_homepage', 'channel_pages', 'stream_manager', 'vod_viewer', 'clip_viewer'],
    },
    {
        id: 'openre-stream',
        domain: 'openre.stream',
        label: 'OpenRe.Stream',
        category: 'core_product',
        status: 'current',
        repoSurface: 'services/openre-stream',
        publicOrigin: 'https://openre.stream',
        internalOrigin: 'http://localhost:4700',
        authRequired: true,
        capabilities: ['stream.ingest', 'stream.restream'],
        eventTopics: ['stream.events'],
        dependsOn: ['openvibe-network', 'openvibe-events'],
        provides: ['rtmp_ingest', 'whip_ingest', 'restream_destinations', 'stream_lifecycle'],
    },
    {
        id: 'openvibe-chat',
        domain: 'openvibe.chat',
        label: 'OpenVibe Chat',
        category: 'core_product',
        status: 'current',
        repoSurface: 'services/openvibe-chat',
        publicOrigin: 'https://openvibe.chat',
        internalOrigin: 'http://localhost:4800',
        authRequired: false,
        capabilities: ['chat.global', 'chat.stream'],
        eventTopics: ['chat.events'],
        dependsOn: ['openvibe-network', 'openvibe-realtime'],
        provides: ['global_chat', 'stream_chat', 'dm', 'moderation'],
    },
    {
        id: 'openvibe-community',
        domain: 'openvibe.community',
        label: 'Pastes',
        category: 'core_product',
        status: 'current',
        repoSurface: 'services/openvibe-community',
        publicOrigin: 'https://openvibe.community',
        internalOrigin: 'http://localhost:4900',
        authRequired: false,
        capabilities: ['community.threads', 'community.pastes', 'community.discord'],
        eventTopics: ['community.events'],
        dependsOn: ['openvibe-network', 'openvibe-realtime', 'openvibe-media'],
        provides: ['threads', 'pastes', 'community_pulse', 'discord_relay', 'comment_threads'],
    },
    {
        id: 'openvibe-games',
        domain: 'openvibe.games',
        label: 'OpenVibe Games',
        category: 'core_product',
        status: 'current',
        repoSurface: 'services/openvibe-games',
        publicOrigin: 'https://openvibe.games',
        internalOrigin: 'http://localhost:5200',
        authRequired: false,
        capabilities: ['games.worlds'],
        eventTopics: ['game.events'],
        dependsOn: ['openvibe-network', 'openvibe-realtime'],
        provides: ['sourcevibe_games', 'world_browser', 'game_runtime'],
    },
    {
        id: 'openvibe-tools',
        domain: 'openvibe.tools',
        label: 'OpenVibe Tools',
        category: 'core_product',
        status: 'planned',
        repoSurface: 'services/openvibe-tools',
        publicOrigin: 'https://openvibe.tools',
        internalOrigin: null,
        authRequired: false,
        capabilities: ['tools.utility'],
        eventTopics: [],
        dependsOn: ['openvibe-network'],
        provides: ['utility_tools'],
    },

    // ── Creator / Economy Surfaces ────────────────────────────────────────────
    {
        id: 'openvibe-tips',
        domain: 'openvibe.tips',
        label: 'OpenVibe Tips',
        category: 'creator_economy',
        status: 'current',
        repoSurface: 'services/openvibe-billing',
        publicOrigin: 'https://openvibe.tips',
        internalOrigin: 'http://localhost:5001',
        authRequired: true,
        capabilities: ['billing.tips'],
        eventTopics: ['tips.events'],
        dependsOn: ['openvibe-billing', 'openvibe-network'],
        provides: ['tips', 'tip_alerts', 'tip_history'],
    },
    {
        id: 'openvibe-vip',
        domain: 'openvibe.vip',
        label: 'OpenVibe VIP',
        category: 'creator_economy',
        status: 'current',
        repoSurface: 'services/openvibe-billing',
        publicOrigin: 'https://openvibe.vip',
        internalOrigin: 'http://localhost:5001',
        authRequired: true,
        capabilities: ['billing.vip'],
        eventTopics: ['vip.events'],
        dependsOn: ['openvibe-billing', 'openvibe-network'],
        provides: ['vip_subscriptions', 'vip_perks', 'vip_management'],
    },
    {
        id: 'openvibe-trade',
        domain: 'openvibe.trade',
        label: 'OpenVibe Trade',
        category: 'creator_economy',
        status: 'planned',
        repoSurface: null,
        publicOrigin: 'https://openvibe.trade',
        internalOrigin: null,
        authRequired: true,
        capabilities: [],
        eventTopics: ['billing.events'],
        dependsOn: ['openvibe-billing', 'openvibe-network'],
        provides: ['item_trading', 'marketplace'],
    },
    {
        id: 'openvibe-host',
        domain: 'openvibe.host',
        label: 'OpenVibe Host',
        category: 'creator_economy',
        status: 'planned',
        repoSurface: null,
        publicOrigin: 'https://openvibe.host',
        internalOrigin: null,
        authRequired: true,
        capabilities: [],
        eventTopics: ['stream.events'],
        dependsOn: ['openvibe-live', 'openvibe-network'],
        provides: ['dedicated_hosting', 'custom_domains'],
    },

    // ── Knowledge / Discovery / Growth Surfaces ───────────────────────────────
    {
        id: 'openvibe-content',
        domain: 'openvibe.codes',
        label: 'OpenVibe Codes',
        category: 'discovery_growth',
        status: 'current',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.codes',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.news'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network'],
        provides: ['content_surfaces', 'codes', 'discovery'],
    },
    {
        id: 'openvibe-wiki',
        domain: 'openvibe.wiki',
        label: 'OpenVibe Wiki',
        category: 'discovery_growth',
        status: 'planned',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.wiki',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.blog'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network', 'openvibe-ai'],
        provides: ['wiki_pages', 'wiki_search'],
    },
    {
        id: 'openvibe-blog',
        domain: 'openvibe.blog',
        label: 'OpenVibe Blog',
        category: 'discovery_growth',
        status: 'planned',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.blog',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.blog'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network'],
        provides: ['blog_posts'],
    },
    {
        id: 'openvibe-news',
        domain: 'openvibe.news',
        label: 'OpenVibe News',
        category: 'discovery_growth',
        status: 'current',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.news',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.news'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network'],
        provides: ['news_feed', 'news_articles'],
    },
    {
        id: 'openvibe-reviews',
        domain: 'openvibe.reviews',
        label: 'OpenVibe Reviews',
        category: 'discovery_growth',
        status: 'current',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.reviews',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.reviews'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network'],
        provides: ['reviews'],
    },
    {
        id: 'openvibe-deals',
        domain: 'openvibe.deals',
        label: 'OpenVibe Deals',
        category: 'discovery_growth',
        status: 'current',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.deals',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.deals'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network'],
        provides: ['deals'],
    },
    {
        id: 'openvibe-coupons',
        domain: 'openvibe.coupons',
        label: 'OpenVibe Coupons',
        category: 'discovery_growth',
        status: 'current',
        repoSurface: 'services/openvibe-content',
        publicOrigin: 'https://openvibe.coupons',
        internalOrigin: 'http://localhost:5500',
        authRequired: false,
        capabilities: ['content.coupons'],
        eventTopics: ['content.events'],
        dependsOn: ['openvibe-network'],
        provides: ['coupons'],
    },
]);

const ECOSYSTEM_CATEGORIES = Object.freeze([
    'kernel',
    'foundation',
    'core_product',
    'creator_economy',
    'discovery_growth',
]);

const ECOSYSTEM_CATEGORY_LABELS = Object.freeze({
    kernel:            'Kernel / Infrastructure',
    foundation:        'Shared Foundations',
    core_product:      'Core Product Surfaces',
    creator_economy:   'Creator / Economy Surfaces',
    discovery_growth:  'Knowledge / Discovery / Growth',
});

const WELL_KNOWN_URLS = Object.freeze({
    network:  'https://openvibe.network',
    auth:     'https://auth.openvibe.network',
    api:      'https://api.openvibe.network',
    admin:    'https://admin.openvibe.network',
    my:       'https://my.openvibe.network',
    themes:   'https://themes.openvibe.network',
    events:   'https://events.openvibe.network',
    realtime: 'wss://realtime.openvibe.network',
    billing:  'https://billing.openvibe.network',
    ai:       'https://ai.openvibe.network',
    media:    'https://openvibe.media',
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function listServices() {
    return ECOSYSTEM_SERVICES.slice();
}

function listServicesByCategory(category) {
    return ECOSYSTEM_SERVICES.filter((s) => s.category === category);
}

function getService(id) {
    return ECOSYSTEM_SERVICES.find((s) => s.id === id) || null;
}

function getServiceByDomain(domain) {
    if (!domain) return null;
    const d = String(domain).toLowerCase();
    return ECOSYSTEM_SERVICES.find((s) => s.domain && s.domain.toLowerCase() === d) || null;
}

function listEcosystemCapabilities() {
    const seen = new Set();
    const caps = [];
    for (const svc of ECOSYSTEM_SERVICES) {
        for (const cap of (svc.capabilities || [])) {
            if (!seen.has(cap)) { seen.add(cap); caps.push(cap); }
        }
    }
    return caps;
}

function listEventTopics() {
    const seen = new Set();
    const topics = [];
    for (const svc of ECOSYSTEM_SERVICES) {
        for (const t of (svc.eventTopics || [])) {
            if (!seen.has(t)) { seen.add(t); topics.push(t); }
        }
    }
    return topics;
}

module.exports = {
    ECOSYSTEM_SERVICES,
    ECOSYSTEM_CATEGORIES,
    ECOSYSTEM_CATEGORY_LABELS,
    WELL_KNOWN_URLS,
    listServices,
    listServicesByCategory,
    getService,
    getServiceByDomain,
    listEcosystemCapabilities,
    listEventTopics,
};
