-- Phase 16: tips creator profiles, VIP creator profiles, and tip-driven chat integration delivery log.
-- Mirrors the SQLite SCHEMA_SQL additions in services/openvibe-billing/server/db.js.

CREATE TABLE IF NOT EXISTS billing_tip_creator_profiles (
    rowid                    BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id                       TEXT PRIMARY KEY,
    owner_type               TEXT NOT NULL,
    owner_id                 TEXT NOT NULL,
    public_slug              TEXT,
    display_name             TEXT NOT NULL,
    description              TEXT,
    currency                 TEXT NOT NULL,
    default_target_type      TEXT,
    default_target_id        TEXT,
    default_visibility       TEXT NOT NULL DEFAULT 'public',
    chat_owner_type          TEXT,
    chat_owner_id            TEXT,
    tts_target_queue         TEXT,
    audio_target_queue       TEXT,
    live_overlay_target      TEXT,
    moderation_settings_json TEXT NOT NULL DEFAULT '{}',
    status                   TEXT NOT NULL DEFAULT 'active',
    metadata_json            TEXT NOT NULL DEFAULT '{}',
    created_at               TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_type, owner_id),
    UNIQUE (public_slug)
);
CREATE INDEX IF NOT EXISTS idx_billing_tip_creators_status ON billing_tip_creator_profiles(status);

CREATE TABLE IF NOT EXISTS billing_vip_creator_profiles (
    rowid                      BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id                         TEXT PRIMARY KEY,
    owner_type                 TEXT NOT NULL,
    owner_id                   TEXT NOT NULL,
    public_slug                TEXT,
    display_name               TEXT NOT NULL,
    description                TEXT,
    content_rating             TEXT NOT NULL DEFAULT 'general',
    requires_age_gate          INTEGER NOT NULL DEFAULT 0,
    allowed_gated_content_json TEXT NOT NULL DEFAULT '[]',
    community_target           TEXT,
    live_target                TEXT,
    blog_target                TEXT,
    wiki_target                TEXT,
    policy_acknowledged_at     TIMESTAMPTZ,
    policy_acknowledged_by     TEXT,
    status                     TEXT NOT NULL DEFAULT 'active',
    metadata_json              TEXT NOT NULL DEFAULT '{}',
    created_at                 TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_type, owner_id),
    UNIQUE (public_slug)
);
CREATE INDEX IF NOT EXISTS idx_billing_vip_creators_status ON billing_vip_creator_profiles(status);

CREATE TABLE IF NOT EXISTS billing_tip_chat_integrations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid            BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    tip_id           TEXT NOT NULL,
    interaction_type TEXT NOT NULL,
    target_kind      TEXT NOT NULL,
    chat_owner_type  TEXT,
    chat_owner_id    TEXT,
    queue_target     TEXT,
    outcome          TEXT NOT NULL,
    detail           TEXT,
    recorded_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_billing_tip_chat_int_tip ON billing_tip_chat_integrations(tip_id);
CREATE INDEX IF NOT EXISTS idx_billing_tip_chat_int_outcome ON billing_tip_chat_integrations(outcome, recorded_at);
