-- Mirrors services/openvibe-events/server/db.js legacy SCHEMA_SQL for runtime parity.
-- Checked-in Postgres migrations are preferred in Postgres mode; schema SQL remains
-- as an idempotent compatibility safety net during the transition.

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    event_id TEXT UNIQUE NOT NULL,
    trace_id TEXT NOT NULL,
    topic TEXT NOT NULL,
    event_type TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    source TEXT NOT NULL,
    actor_type TEXT,
    actor_id TEXT,
    timestamp TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_events_topic_time ON events(topic, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_trace ON events(trace_id);

CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    subscription_id TEXT UNIQUE NOT NULL,
    consumer TEXT NOT NULL,
    topic TEXT NOT NULL,
    event_type TEXT,
    delivery TEXT NOT NULL,
    target_url TEXT,
    internal_key TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_topic_active ON subscriptions(topic, active);

CREATE TABLE IF NOT EXISTS delivery_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    event_id TEXT NOT NULL,
    subscription_id TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (event_id, subscription_id)
);
CREATE INDEX IF NOT EXISTS idx_queue_pending ON delivery_queue(state, next_attempt_at);

CREATE TABLE IF NOT EXISTS dead_letters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    event_id TEXT NOT NULL,
    subscription_id TEXT NOT NULL,
    attempts INTEGER NOT NULL,
    last_error TEXT,
    failed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dlq_event ON dead_letters(event_id);
