-- Mirrors services/openvibe-network/server/db.js legacy SCHEMA_SQL for runtime parity.
-- Checked-in Postgres migrations are preferred in Postgres mode; schema SQL remains
-- as an idempotent compatibility safety net during the transition.

CREATE TABLE IF NOT EXISTS user_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    user_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    owner TEXT NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    data_json TEXT NOT NULL,
    updated_by_actor_type TEXT,
    updated_by_actor_id TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, namespace)
);
CREATE INDEX IF NOT EXISTS idx_user_modules_user ON user_modules(user_id);

CREATE TABLE IF NOT EXISTS user_modules_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    user_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    schema_version INTEGER NOT NULL,
    data_json TEXT NOT NULL,
    actor_type TEXT,
    actor_id TEXT,
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_modules_history ON user_modules_history(user_id, namespace, recorded_at DESC);

CREATE TABLE IF NOT EXISTS service_registry (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    service_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    description TEXT,
    internal_url TEXT,
    public_url TEXT,
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    topics_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    last_heartbeat TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS capability_registry (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    capability_id TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    owner_service TEXT NOT NULL,
    description TEXT,
    input_schema_json TEXT NOT NULL DEFAULT '{}',
    output_schema_json TEXT NOT NULL DEFAULT '{}',
    policy_json TEXT NOT NULL DEFAULT '{}',
    rate_limit_json TEXT NOT NULL DEFAULT '{}',
    emits_topics_json TEXT NOT NULL DEFAULT '[]',
    deprecated INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (capability_id, version)
);

CREATE TABLE IF NOT EXISTS capability_invocations (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    invocation_id TEXT PRIMARY KEY,
    capability_id TEXT NOT NULL,
    capability_version INTEGER NOT NULL,
    actor_type TEXT,
    actor_id TEXT,
    trace_id TEXT NOT NULL,
    idempotency_key TEXT,
    target_service TEXT,
    request_json TEXT NOT NULL DEFAULT '{}',
    response_json TEXT,
    error_json TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    http_status INTEGER NOT NULL DEFAULT 202,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (capability_id, actor_type, actor_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_capability_invocations_trace ON capability_invocations(trace_id);
CREATE INDEX IF NOT EXISTS idx_capability_invocations_actor ON capability_invocations(actor_type, actor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS contract_registry (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    contract_id TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    kind TEXT NOT NULL,
    owner_service TEXT NOT NULL,
    schema_json TEXT NOT NULL,
    description TEXT,
    deprecated INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (contract_id, version)
);

CREATE TABLE IF NOT EXISTS url_registry_overlay (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    actor_type TEXT,
    actor_id TEXT,
    action TEXT NOT NULL,
    resource TEXT NOT NULL,
    outcome TEXT NOT NULL,
    detail_json TEXT,
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor_type, actor_id, recorded_at DESC);
