-- Mirrors services/openvibe-network/server/db.js legacy SCHEMA_SQL for runtime parity.
-- Checked-in Postgres migrations are preferred in Postgres mode; schema SQL remains
-- as an idempotent compatibility safety net during the transition.

CREATE TABLE IF NOT EXISTS user_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    user_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    owner TEXT NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    data_json TEXT NOT NULL,
    updated_by_actor_type TEXT,
    updated_by_actor_id TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, namespace)
);
CREATE INDEX IF NOT EXISTS idx_user_modules_user ON user_modules(user_id);

CREATE TABLE IF NOT EXISTS user_modules_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    user_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    schema_version INTEGER NOT NULL,
    data_json TEXT NOT NULL,
    actor_type TEXT,
    actor_id TEXT,
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_modules_history ON user_modules_history(user_id, namespace, recorded_at DESC);

CREATE TABLE IF NOT EXISTS service_registry (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    service_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    description TEXT,
    internal_url TEXT,
    public_url TEXT,
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    topics_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    last_heartbeat TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS capability_registry (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    capability_id TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    owner_service TEXT NOT NULL,
    description TEXT,
    input_schema_json TEXT NOT NULL DEFAULT '{}',
    output_schema_json TEXT NOT NULL DEFAULT '{}',
    policy_json TEXT NOT NULL DEFAULT '{}',
    rate_limit_json TEXT NOT NULL DEFAULT '{}',
    emits_topics_json TEXT NOT NULL DEFAULT '[]',
    deprecated INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (capability_id, version)
);

CREATE TABLE IF NOT EXISTS capability_invocations (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    invocation_id TEXT PRIMARY KEY,
    capability_id TEXT NOT NULL,
    capability_version INTEGER NOT NULL,
    actor_type TEXT,
    actor_id TEXT,
    trace_id TEXT NOT NULL,
    idempotency_key TEXT,
    target_service TEXT,
    request_json TEXT NOT NULL DEFAULT '{}',
    response_json TEXT,
    error_json TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    http_status INTEGER NOT NULL DEFAULT 202,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (capability_id, actor_type, actor_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_capability_invocations_trace ON capability_invocations(trace_id);
CREATE INDEX IF NOT EXISTS idx_capability_invocations_actor ON capability_invocations(actor_type, actor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS contract_registry (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    contract_id TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    kind TEXT NOT NULL,
    owner_service TEXT NOT NULL,
    schema_json TEXT NOT NULL,
    description TEXT,
    deprecated INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (contract_id, version)
);

CREATE TABLE IF NOT EXISTS url_registry_overlay (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    actor_type TEXT,
    actor_id TEXT,
    action TEXT NOT NULL,
    resource TEXT NOT NULL,
    outcome TEXT NOT NULL,
    detail_json TEXT,
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor_type, actor_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS auth_users (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT,
    email TEXT UNIQUE,
    avatar_url TEXT,
    password_hash TEXT,
    password_algorithm TEXT NOT NULL DEFAULT 'none',
    password_updated_at TIMESTAMPTZ,
    primary_source TEXT,
    is_banned INTEGER NOT NULL DEFAULT 0,
    ban_reason TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS auth_anon_users (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    anon_number INTEGER NOT NULL UNIQUE,
    session_token TEXT UNIQUE,
    display_name TEXT,
    preferences_json TEXT NOT NULL DEFAULT '{}',
    total_messages INTEGER NOT NULL DEFAULT 0,
    total_commands INTEGER NOT NULL DEFAULT 0,
    primary_source TEXT,
    legacy_source TEXT,
    legacy_id TEXT,
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_anon_users_number ON auth_anon_users(anon_number);

CREATE TABLE IF NOT EXISTS auth_anon_ip_links (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    anon_user_id TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    source TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (anon_user_id, ip_address)
);
CREATE INDEX IF NOT EXISTS idx_auth_anon_ip_links_ip ON auth_anon_ip_links(ip_address, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_auth_anon_ip_links_anon ON auth_anon_ip_links(anon_user_id, last_seen DESC);

CREATE TABLE IF NOT EXISTS auth_anon_fingerprints (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    anon_user_id TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    source TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (anon_user_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_auth_anon_fingerprints_lookup ON auth_anon_fingerprints(fingerprint, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_auth_anon_fingerprints_anon ON auth_anon_fingerprints(anon_user_id, last_seen DESC);

CREATE TABLE IF NOT EXISTS auth_authorization_codes (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    code_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    client_id TEXT,
    redirect_uri TEXT,
    scope TEXT NOT NULL,
    nonce TEXT,
    state TEXT,
    code_challenge TEXT,
    code_challenge_method TEXT,
    session_id TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_codes_user ON auth_authorization_codes(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    token_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    client_id TEXT,
    scope TEXT NOT NULL,
    session_id TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    rotated_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON auth_refresh_tokens(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS auth_sessions (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    user_agent TEXT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    metadata_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS control_notifications (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    sender_user_id TEXT,
    type TEXT NOT NULL,
    category TEXT,
    priority TEXT NOT NULL DEFAULT 'normal',
    title TEXT NOT NULL,
    message TEXT,
    icon TEXT,
    sender_name TEXT,
    sender_avatar TEXT,
    service TEXT,
    url TEXT,
    rich_content_json TEXT,
    is_read INTEGER NOT NULL DEFAULT 0,
    is_dismissed INTEGER NOT NULL DEFAULT 0,
    is_emailed INTEGER NOT NULL DEFAULT 0,
    read_at TIMESTAMPTZ,
    dismissed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_control_notifications_user ON control_notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_control_notifications_unread ON control_notifications(user_id, is_read, is_dismissed, created_at DESC);

CREATE TABLE IF NOT EXISTS control_oauth_clients (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    redirect_uris_json TEXT NOT NULL DEFAULT '[]',
    is_first_party INTEGER NOT NULL DEFAULT 0,
    client_secret_redacted INTEGER NOT NULL DEFAULT 1,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_control_oauth_clients_name ON control_oauth_clients(name);

CREATE TABLE IF NOT EXISTS social_follows (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT 'network',
    follower_user_id TEXT NOT NULL,
    followed_user_id TEXT NOT NULL,
    email_notify INTEGER NOT NULL DEFAULT 0,
    push_notify INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (follower_user_id, followed_user_id, scope)
);
CREATE INDEX IF NOT EXISTS idx_social_follows_follower ON social_follows(follower_user_id, scope, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_follows_followed ON social_follows(followed_user_id, scope, created_at DESC);
