-- Add first-class anonymous runtime identities so migrated anon numbers can be
-- projected into openvibe-network and reused across OpenVibe surfaces.

CREATE TABLE IF NOT EXISTS auth_anon_users (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    anon_number INTEGER NOT NULL UNIQUE,
    session_token TEXT UNIQUE,
    display_name TEXT,
    preferences_json TEXT NOT NULL DEFAULT '{}',
    total_messages INTEGER NOT NULL DEFAULT 0,
    total_commands INTEGER NOT NULL DEFAULT 0,
    primary_source TEXT,
    legacy_source TEXT,
    legacy_id TEXT,
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_anon_users_number ON auth_anon_users(anon_number);
