-- Preserve legacy IP/fingerprint continuity for numbered anonymous identities
-- so imported anon mappings survive the OpenVibe cutover.

CREATE TABLE IF NOT EXISTS auth_anon_ip_links (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    anon_user_id TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    source TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (anon_user_id, ip_address)
);
CREATE INDEX IF NOT EXISTS idx_auth_anon_ip_links_ip ON auth_anon_ip_links(ip_address, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_auth_anon_ip_links_anon ON auth_anon_ip_links(anon_user_id, last_seen DESC);

CREATE TABLE IF NOT EXISTS auth_anon_fingerprints (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    anon_user_id TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    source TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (anon_user_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_auth_anon_fingerprints_lookup ON auth_anon_fingerprints(fingerprint, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_auth_anon_fingerprints_anon ON auth_anon_fingerprints(anon_user_id, last_seen DESC);