-- Mirrors services/openvibe-live/server/db.js legacy SCHEMA_SQL for runtime parity.
-- Checked-in Postgres migrations are preferred in Postgres mode; schema SQL remains
-- as an idempotent compatibility safety net during the transition.

CREATE TABLE IF NOT EXISTS live_channels (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    display_name TEXT,
    owner_user_id TEXT,
    description TEXT,
    avatar_url TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS live_streams (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    channel_slug TEXT NOT NULL,
    channel_id TEXT,
    status TEXT NOT NULL DEFAULT 'created',
    title TEXT,
    category TEXT,
    thumbnail_url TEXT,
    embed_url TEXT,
    vod_media_id TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_live_streams_channel ON live_streams(channel_slug);
CREATE INDEX IF NOT EXISTS idx_live_streams_status ON live_streams(status);

CREATE TABLE IF NOT EXISTS mirror_state (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    stream_id TEXT PRIMARY KEY,
    channel_slug TEXT,
    mirrored_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    details_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS legacy_id_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    source TEXT NOT NULL,
    kind TEXT NOT NULL,
    legacy_id TEXT NOT NULL,
    new_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source, kind, legacy_id)
);
