-- Phase 16: per-channel and per-stream product integrations (chat-room, tips,
-- vip, audio-overlay, ai-assist). Mirrors live_stream_integrations addition in
-- services/openvibe-live/server/db.js SCHEMA_SQL.

CREATE TABLE IF NOT EXISTS live_stream_integrations (
    rowid           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id              TEXT PRIMARY KEY,
    owner_kind      TEXT NOT NULL,
    owner_ref       TEXT NOT NULL,
    channel_slug    TEXT,
    target_kind     TEXT NOT NULL,
    target_url      TEXT,
    status          TEXT NOT NULL DEFAULT 'unavailable',
    detail          TEXT,
    metadata_json   TEXT NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_kind, owner_ref, target_kind)
);
CREATE INDEX IF NOT EXISTS idx_live_stream_int_channel ON live_stream_integrations(channel_slug);
CREATE INDEX IF NOT EXISTS idx_live_stream_int_status ON live_stream_integrations(status, target_kind);
