-- OpenVibe — content Phase 16 schema additions: review decisions and
-- distribution audit. These mirror the SQLite schema added in
-- services/openvibe-content/server/db/sqlite.js for the same milestone.

CREATE TABLE IF NOT EXISTS content_review_decisions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id             TEXT NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
    decision            TEXT NOT NULL,
    from_state          TEXT,
    to_state            TEXT,
    reviewer_actor_type TEXT,
    reviewer_actor_id   TEXT,
    notes               TEXT,
    metadata_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    decided_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_content_review_item ON content_review_decisions(item_id, decided_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_review_decision ON content_review_decisions(decision, decided_at DESC);

CREATE TABLE IF NOT EXISTS content_distribution_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         TEXT NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
    surface         TEXT NOT NULL,
    channel         TEXT NOT NULL,
    outcome         TEXT NOT NULL,
    actor_type      TEXT,
    actor_id        TEXT,
    error_message   TEXT,
    metadata_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
    recorded_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_content_distribution_item ON content_distribution_audit(item_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_distribution_outcome ON content_distribution_audit(outcome, recorded_at DESC);
