'use strict';

const assert = require('assert');
const path = require('path');

const canonical = require('../canonical-bootstrap');

(function listsKnownServices() {
    const services = canonical.listKnownServices();
    assert.ok(services.includes('openvibe-network'));
    assert.ok(services.includes('openvibe-billing'));
    assert.ok(services.includes('openvibe-content'));
})();

(function describeNetworkBootstrap() {
    const descriptor = canonical.describeBootstrapSource('openvibe-network');
    assert.strictEqual(descriptor.service, 'openvibe-network');
    assert.strictEqual(descriptor.has_checked_in_migrations, true);
    assert.strictEqual(descriptor.migration_source, 'checked-in');
    assert.strictEqual(descriptor.bootstrap_source, 'canonical-migrations');
    assert.strictEqual(descriptor.schema_sql_reconciled, true);
    assert.ok(descriptor.migration_files.length >= 1);
    assert.ok(descriptor.migration_files.some((file) => file.endsWith('001_init.sql')));
})();

(function describeLegacyBootstrap() {
    const descriptor = canonical.describeBootstrapSource('openvibe-network', { usesLegacyBootstrapSql: true });
    assert.strictEqual(descriptor.uses_legacy_bootstrap_sql, true);
    assert.strictEqual(descriptor.bootstrap_source, 'legacy-schema-sql-literal');
    assert.strictEqual(descriptor.schema_sql_reconciled, false);
})();

(function describeUnknownService() {
    const descriptor = canonical.describeBootstrapSource('made-up-service');
    assert.strictEqual(descriptor.has_checked_in_migrations, false);
    assert.strictEqual(descriptor.migration_source, 'absent');
    assert.strictEqual(descriptor.bootstrap_source, 'none');
    assert.strictEqual(descriptor.schema_sql_reconciled, false);
})();

(function loadCanonicalSql() {
    const sql = canonical.loadCanonicalBootstrapSql('openvibe-network');
    assert.ok(sql && sql.length > 0);
    assert.ok(/create\s+table/i.test(sql));
})();

(function customDirOverride() {
    const descriptor = canonical.describeBootstrapSource('arbitrary', { migrationDir: path.join(__dirname, 'no-such-dir') });
    assert.strictEqual(descriptor.has_checked_in_migrations, false);
})();

(function convertsBigintIdentity() {
    const sqlite = canonical.convertCanonicalMigrationsToSqlite(
        'CREATE TABLE x (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, t TIMESTAMPTZ, j JSONB, n BIGINT);'
    );
    assert.ok(/INTEGER PRIMARY KEY AUTOINCREMENT/.test(sqlite), sqlite);
    assert.ok(/\bDATETIME\b/.test(sqlite), sqlite);
    assert.ok(/\bTEXT\b/.test(sqlite), sqlite);
    assert.ok(!/\bBIGINT\b/.test(sqlite), sqlite);
    assert.ok(!/\bJSONB\b/.test(sqlite), sqlite);
    assert.ok(!/\bTIMESTAMPTZ\b/.test(sqlite), sqlite);
})();

(function dropsGeneratedAlwaysStored() {
    const sqlite = canonical.convertCanonicalMigrationsToSqlite([
        'CREATE TABLE y (',
        '    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,',
        '    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,',
        '    name TEXT',
        ');',
    ].join('\n'));
    assert.ok(!/GENERATED ALWAYS AS/i.test(sqlite), sqlite);
    assert.ok(/INTEGER PRIMARY KEY AUTOINCREMENT/.test(sqlite));
})();

(function dropsDoBlocks() {
    const sqlite = canonical.convertCanonicalMigrationsToSqlite([
        'CREATE TABLE z (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);',
        "DO $$ BEGIN RAISE NOTICE 'pg-only'; END $$;",
    ].join('\n'));
    assert.ok(!/DO \$\$/.test(sqlite), sqlite);
    assert.ok(/CREATE TABLE z/.test(sqlite));
})();

(function loadsConvertedForKnownService() {
    const sqlite = canonical.loadCanonicalBootstrapSqlForSqlite('openvibe-events');
    assert.ok(sqlite && sqlite.length > 0);
    assert.ok(!/\bBIGINT\b/.test(sqlite), 'BIGINT should be normalized in converted bootstrap');
    assert.ok(!/\bTIMESTAMPTZ\b/.test(sqlite));
    assert.ok(!/GENERATED ALWAYS AS/i.test(sqlite));
})();

(function convertedBootstrapExecutesUnderSqlite() {
    let Database;
    try {
        Database = require('better-sqlite3');
    } catch (error) {
        console.log('canonical-bootstrap: skipping live SQLite execution (better-sqlite3 missing)');
        return;
    }
    // Services whose Postgres canonical migrations should round-trip cleanly
    // through the SQLite-bootstrap converter. Chat and content are intentionally
    // excluded for now because their migrations rely on Postgres-only constructs
    // (CREATE INDEX IF NOT EXISTS table-qualified lookups, FOREIGN KEY ON
    // expressions referencing reserved-word columns) that the conservative
    // converter does not yet handle. Phase 16+ slice 1.b should close those.
    const services = [
        'openvibe-network',
        'openvibe-events',
        'openvibe-media',
        'openvibe-live',
        'openre-stream',
        'openvibe-community',
        'openvibe-billing',
        'openvibe-ai',
        'openvibe-games',
    ];
    for (const serviceName of services) {
        const sqlite = canonical.loadCanonicalBootstrapSqlForSqlite(serviceName);
        assert.ok(sqlite && sqlite.length > 0, `expected canonical SQLite bootstrap for ${serviceName}`);
        const db = new Database(':memory:');
        try {
            db.exec(sqlite);
        } catch (error) {
            assert.fail(`converted bootstrap failed to execute for ${serviceName}: ${error.message}`);
        } finally {
            db.close();
        }
    }
})();

console.log('canonical-bootstrap: OK');
