'use strict';

const assert = require('assert');

const {
    normalizeSchemaSql,
    replacePositionalParameters,
    splitSqlStatements,
    translateSqliteToPostgres,
} = require('../sql-compat');

function testSplitStatements() {
    const statements = splitSqlStatements(`CREATE TABLE demo (id INTEGER PRIMARY KEY AUTOINCREMENT, note TEXT DEFAULT 'a;b');\nINSERT OR IGNORE INTO demo (note) VALUES ('still;one');`);
    assert.strictEqual(statements.length, 2);
}

function testParameterReplacement() {
    const sql = replacePositionalParameters(`SELECT * FROM chat_messages WHERE room_id = ? AND body != '?' LIMIT ?`);
    assert.strictEqual(sql, `SELECT * FROM chat_messages WHERE room_id = $1 AND body != '?' LIMIT $2`);
}

function testSchemaNormalization() {
    const sql = normalizeSchemaSql(`CREATE TABLE IF NOT EXISTS auth_users (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)`);
    assert.ok(sql.includes('id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'));
    assert.ok(sql.includes('rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE'));
    assert.ok(sql.includes('created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP'));
}

function testQueryTranslation() {
    const sql = translateSqliteToPostgres(`INSERT OR IGNORE INTO chat_legacy_map (source, kind, legacy_id, new_id) VALUES (?, ?, ?, ?)`, { mode: 'run' });
    assert.ok(sql.includes('ON CONFLICT DO NOTHING'));
    assert.ok(sql.includes('RETURNING *'));
    assert.ok(!sql.includes('RETURNING rowid'));
    assert.ok(sql.includes('$1'));
    assert.ok(sql.includes('$4'));
}

function testAlterTableTranslation() {
    const sql = normalizeSchemaSql('ALTER TABLE chat_participants ADD COLUMN last_read_at DATETIME');
    assert.strictEqual(sql, 'ALTER TABLE chat_participants ADD COLUMN IF NOT EXISTS last_read_at TIMESTAMPTZ');
}

function testFunctionTranslation() {
    const sql = translateSqliteToPostgres(`SELECT lower(hex(randomblob(8))) AS h, STRFTIME('%Y-%m-%d %H:%M:%f', 'now') AS created_at`, { mode: 'get' });
    assert.ok(sql.includes('substring(md5('));
    assert.ok(sql.includes('CURRENT_TIMESTAMP'));
}

function testDatetimeFunctionTranslation() {
    const sql = translateSqliteToPostgres(`
        SELECT datetime(last_login_at) AS last_login_at,
               datetime(expires_at) > datetime('now') AS active,
               datetime('now', '+' || ? || ' seconds') AS retry_at
          FROM auth_sessions
         LIMIT ?
    `, { mode: 'all' });
    assert.ok(!sql.includes('TIMESTAMPTZ('));
    assert.ok(sql.includes('last_login_at AS last_login_at'));
    assert.ok(sql.includes('expires_at) > CURRENT_TIMESTAMP') || sql.includes('expires_at > CURRENT_TIMESTAMP'));
    assert.ok(sql.includes("CURRENT_TIMESTAMP + (('+' || $1 || ' seconds')::interval)"));
    assert.ok(sql.includes('LIMIT $2'));
}

function main() {
    testSplitStatements();
    testParameterReplacement();
    testSchemaNormalization();
    testQueryTranslation();
    testFunctionTranslation();
    testDatetimeFunctionTranslation();
    testAlterTableTranslation();
    console.log('openvibe-persistence sql compat tests OK');
}

main();
