-- Mirrors services/openvibe-games/server/db.js legacy SCHEMA_SQL for runtime parity.
-- Checked-in Postgres migrations are preferred in Postgres mode; schema SQL remains
-- as an idempotent compatibility safety net during the transition.

CREATE TABLE IF NOT EXISTS game_players (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT PRIMARY KEY,
    display_name TEXT,
    avatar_url TEXT,
    class_name TEXT NOT NULL DEFAULT 'wanderer',
    world_id TEXT NOT NULL DEFAULT 'main',
    zone TEXT NOT NULL DEFAULT 'outpost',
    x REAL NOT NULL DEFAULT 4096,
    y REAL NOT NULL DEFAULT 4096,
    coins INTEGER NOT NULL DEFAULT 0,
    loyalty_points INTEGER NOT NULL DEFAULT 0,
    mining_xp INTEGER NOT NULL DEFAULT 0,
    fishing_xp INTEGER NOT NULL DEFAULT 0,
    woodcut_xp INTEGER NOT NULL DEFAULT 0,
    farming_xp INTEGER NOT NULL DEFAULT 0,
    combat_xp INTEGER NOT NULL DEFAULT 0,
    crafting_xp INTEGER NOT NULL DEFAULT 0,
    smithing_xp INTEGER NOT NULL DEFAULT 0,
    agility_xp INTEGER NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL DEFAULT 100,
    max_hp INTEGER NOT NULL DEFAULT 100,
    stamina INTEGER NOT NULL DEFAULT 100,
    max_stamina INTEGER NOT NULL DEFAULT 100,
    equip_pickaxe TEXT,
    equip_rod TEXT,
    equip_axe TEXT,
    equip_hat TEXT NOT NULL DEFAULT '',
    equip_weapon TEXT NOT NULL DEFAULT '',
    equip_armor TEXT NOT NULL DEFAULT '',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_game_players_world ON game_players(world_id, zone);

CREATE TABLE IF NOT EXISTS game_world_state (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    value_type TEXT NOT NULL DEFAULT 'json',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_inventory (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, item_id)
);
CREATE INDEX IF NOT EXISTS idx_game_inventory_user ON game_inventory(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS game_bank (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, item_id)
);

CREATE TABLE IF NOT EXISTS game_structures (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    world_id TEXT NOT NULL DEFAULT 'main',
    x REAL NOT NULL,
    y REAL NOT NULL,
    owner_id TEXT,
    data_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_game_structures_world ON game_structures(world_id, x, y);

CREATE TABLE IF NOT EXISTS game_farm_plots (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    plot_index INTEGER NOT NULL,
    seed_id TEXT,
    stage TEXT NOT NULL DEFAULT 'empty',
    planted_at TIMESTAMPTZ,
    watered_at TIMESTAMPTZ,
    ready_at TIMESTAMPTZ,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, plot_index)
);

CREATE TABLE IF NOT EXISTS game_recipes (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    recipe_id TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    unlocked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS game_effects (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    effect_type TEXT NOT NULL,
    effect_id TEXT,
    expires_at TIMESTAMPTZ,
    charges INTEGER,
    data_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_battle_stats (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT PRIMARY KEY,
    battles_won INTEGER NOT NULL DEFAULT 0,
    battles_lost INTEGER NOT NULL DEFAULT 0,
    total_stolen REAL NOT NULL DEFAULT 0,
    total_lost REAL NOT NULL DEFAULT 0,
    kill_streak INTEGER NOT NULL DEFAULT 0,
    best_streak INTEGER NOT NULL DEFAULT 0,
    fatalities INTEGER NOT NULL DEFAULT 0,
    kills INTEGER NOT NULL DEFAULT 0,
    deaths INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_dungeon_runs (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    dungeon_id TEXT NOT NULL,
    floor_reached INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'active',
    party_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS game_leaderboard (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    board TEXT NOT NULL,
    rank INTEGER NOT NULL DEFAULT 0,
    user_id TEXT,
    username TEXT,
    value INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_game_leaderboard_board ON game_leaderboard(board, rank ASC, value DESC);

CREATE TABLE IF NOT EXISTS game_fish_collection (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    fish_id TEXT NOT NULL,
    count INTEGER NOT NULL DEFAULT 0,
    best_weight REAL NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    first_caught TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, fish_id)
);

CREATE TABLE IF NOT EXISTS game_daily_quests (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    quest_date TEXT NOT NULL,
    quest_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    progress INTEGER NOT NULL DEFAULT 0,
    goal INTEGER NOT NULL DEFAULT 1,
    reward_json TEXT NOT NULL DEFAULT '{}',
    claimed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, quest_date, quest_id)
);

CREATE TABLE IF NOT EXISTS game_achievements (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    achievement_id TEXT NOT NULL,
    title TEXT,
    description TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    unlocked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, achievement_id)
);

CREATE TABLE IF NOT EXISTS game_cosmetics (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    slot TEXT NOT NULL,
    item_id TEXT NOT NULL,
    equipped INTEGER NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'import',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    acquired_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, slot, item_id)
);

CREATE TABLE IF NOT EXISTS game_tags (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'import',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    granted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, tag_id)
);

CREATE TABLE IF NOT EXISTS game_equipped_tags (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT PRIMARY KEY,
    tag_id TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_tag_guardian_defeats (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT PRIMARY KEY,
    defeated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_legacy_map (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    source TEXT NOT NULL,
    kind TEXT NOT NULL,
    legacy_id TEXT NOT NULL,
    new_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source, kind, legacy_id)
);

CREATE TABLE IF NOT EXISTS canvas_settings (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'json',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS canvas_tiles (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    color_index INTEGER NOT NULL,
    user_id TEXT,
    username TEXT,
    ip_address TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (x, y)
);

CREATE TABLE IF NOT EXISTS canvas_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    action_type TEXT NOT NULL,
    x INTEGER,
    y INTEGER,
    prev_color_index INTEGER,
    color_index INTEGER,
    user_id TEXT,
    username TEXT,
    ip_address TEXT,
    meta_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_canvas_actions_created ON canvas_actions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_canvas_actions_user ON canvas_actions(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS canvas_region_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    label TEXT DEFAULT '',
    mode TEXT NOT NULL DEFAULT 'locked',
    x1 INTEGER NOT NULL,
    y1 INTEGER NOT NULL,
    x2 INTEGER NOT NULL,
    y2 INTEGER NOT NULL,
    reason TEXT DEFAULT '',
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS canvas_snapshots (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    board_data_json TEXT NOT NULL,
    created_by TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS canvas_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    user_id TEXT,
    ip_address TEXT,
    action_type TEXT NOT NULL DEFAULT 'ban',
    reason TEXT DEFAULT '',
    expires_at TIMESTAMPTZ,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS canvas_user_overrides (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id TEXT PRIMARY KEY,
    cooldown_seconds INTEGER,
    placements_per_minute INTEGER,
    bypass_read_only INTEGER NOT NULL DEFAULT 0,
    note TEXT DEFAULT '',
    updated_by TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
