-- Mirrors services/openvibe-media/server/db.js legacy SCHEMA_SQL for runtime parity.
-- Checked-in Postgres migrations are preferred in Postgres mode; schema SQL remains
-- as an idempotent compatibility safety net during the transition.

CREATE TABLE IF NOT EXISTS media_objects (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'initialized',
    visibility TEXT NOT NULL DEFAULT 'public',
    storage_tier TEXT NOT NULL DEFAULT 'hot',
    storage_provider TEXT NOT NULL DEFAULT 'local',
    storage_key TEXT,
    public_url TEXT,
    cdn_url TEXT,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    mime_type TEXT,
    sha256 TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_by_actor_type TEXT,
    created_by_actor_id TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_media_owner ON media_objects(owner_type, owner_id);
CREATE INDEX IF NOT EXISTS idx_media_ns ON media_objects(namespace);
CREATE INDEX IF NOT EXISTS idx_media_status ON media_objects(status);
CREATE INDEX IF NOT EXISTS idx_media_visible ON media_objects(visibility);
CREATE INDEX IF NOT EXISTS idx_media_sha256 ON media_objects(sha256);

CREATE TABLE IF NOT EXISTS media_derivatives (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    parent_media_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    label TEXT,
    storage_provider TEXT NOT NULL DEFAULT 'local',
    storage_key TEXT,
    public_url TEXT,
    mime_type TEXT,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_media_id) REFERENCES media_objects(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_derivative_parent ON media_derivatives(parent_media_id);
CREATE INDEX IF NOT EXISTS idx_derivative_kind ON media_derivatives(kind);

CREATE TABLE IF NOT EXISTS media_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    next_attempt_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_jobs_state ON media_jobs(state, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_jobs_media ON media_jobs(media_id);

CREATE TABLE IF NOT EXISTS media_quotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    max_storage_bytes INTEGER NOT NULL DEFAULT 0,
    max_upload_bytes INTEGER NOT NULL DEFAULT 0,
    max_file_count INTEGER NOT NULL DEFAULT 0,
    allowed_mime_prefixes_json TEXT NOT NULL DEFAULT '[]',
    allowed_types_json TEXT NOT NULL DEFAULT '[]',
    unlimited INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_type, owner_id, namespace)
);

CREATE TABLE IF NOT EXISTS media_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    total_bytes INTEGER NOT NULL DEFAULT 0,
    hot_bytes INTEGER NOT NULL DEFAULT 0,
    warm_bytes INTEGER NOT NULL DEFAULT 0,
    cold_bytes INTEGER NOT NULL DEFAULT 0,
    file_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_type, owner_id, namespace)
);

CREATE TABLE IF NOT EXISTS media_lifecycle_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT,
    from_tier TEXT,
    to_tier TEXT,
    actor_type TEXT,
    actor_id TEXT,
    detail_json TEXT NOT NULL DEFAULT '{}',
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_lifecycle_media ON media_lifecycle_audit(media_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS media_legacy_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    source TEXT NOT NULL,
    kind TEXT NOT NULL,
    legacy_id TEXT NOT NULL,
    media_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source, kind, legacy_id)
);

CREATE TABLE IF NOT EXISTS media_object_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    provider_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'canonical',
    storage_key TEXT NOT NULL,
    bucket TEXT,
    endpoint TEXT,
    region TEXT,
    public_url TEXT,
    signed_url_required INTEGER NOT NULL DEFAULT 0,
    checksum_sha256 TEXT,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (media_id, provider_name, role, storage_key)
);
CREATE INDEX IF NOT EXISTS idx_media_locations_media ON media_object_locations(media_id, role, status);

CREATE TABLE IF NOT EXISTS media_upload_sessions (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    media_id TEXT NOT NULL,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    namespace TEXT NOT NULL,
    provider_name TEXT NOT NULL,
    storage_key TEXT NOT NULL,
    upload_mode TEXT NOT NULL DEFAULT 'multipart',
    status TEXT NOT NULL DEFAULT 'initialized',
    token TEXT,
    mime_type TEXT,
    expected_size_bytes INTEGER,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_media_upload_sessions_media ON media_upload_sessions(media_id, status);

CREATE TABLE IF NOT EXISTS media_upload_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    upload_id TEXT NOT NULL,
    part_number INTEGER NOT NULL,
    etag TEXT,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'signed',
    token TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (upload_id, part_number)
);
CREATE INDEX IF NOT EXISTS idx_media_upload_parts_upload ON media_upload_parts(upload_id, status);

CREATE TABLE IF NOT EXISTS media_size_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    violation_type TEXT NOT NULL,
    detail_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stream_recordings (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    stream_id TEXT NOT NULL,
    channel_slug TEXT,
    media_id TEXT,
    status TEXT NOT NULL DEFAULT 'recording',
    storage_key TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_stream_recordings_stream ON stream_recordings(stream_id, status);

CREATE TABLE IF NOT EXISTS recording_segments (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    recording_id TEXT NOT NULL,
    segment_index INTEGER NOT NULL,
    start_ms INTEGER NOT NULL DEFAULT 0,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    media_id TEXT,
    storage_key TEXT,
    playlist_key TEXT,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'ready',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (recording_id, segment_index)
);

CREATE TABLE IF NOT EXISTS clip_projects (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    source_stream_id TEXT,
    source_media_id TEXT,
    owner_user_id TEXT,
    title TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    start_ms INTEGER NOT NULL DEFAULT 0,
    end_ms INTEGER NOT NULL DEFAULT 0,
    playback_media_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clip_exports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    clip_id TEXT NOT NULL,
    job_id TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    media_id TEXT,
    error TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transcript_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    start_ms INTEGER NOT NULL DEFAULT 0,
    end_ms INTEGER NOT NULL DEFAULT 0,
    text TEXT NOT NULL,
    confidence REAL,
    speaker_label TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_transcript_segments_media ON transcript_segments(media_id, start_ms);

CREATE TABLE IF NOT EXISTS scene_markers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    start_ms INTEGER NOT NULL DEFAULT 0,
    end_ms INTEGER NOT NULL DEFAULT 0,
    score REAL,
    source TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_scene_markers_media ON scene_markers(media_id, start_ms);

CREATE TABLE IF NOT EXISTS analysis_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    media_id TEXT NOT NULL,
    candidate_type TEXT NOT NULL,
    start_ms INTEGER NOT NULL DEFAULT 0,
    end_ms INTEGER NOT NULL DEFAULT 0,
    score REAL NOT NULL DEFAULT 0,
    rationale_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'queued',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_analysis_candidates_media ON analysis_candidates(media_id, candidate_type, status);
