-- openvibe-tips Postgres migration 001 — initial schema
-- Mirror of SCHEMA_SQL in server/db.js.
-- Conventions: rowid first, TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP (not NOW()),
-- inline UNIQUE on columns that have it inline in the SQLite schema.

CREATE TABLE IF NOT EXISTS tips_creators (
    rowid           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL,
    slug            TEXT NOT NULL UNIQUE,
    display_name    TEXT NOT NULL,
    bio             TEXT,
    avatar_url      TEXT,
    accent_color    TEXT NOT NULL DEFAULT '#f59e0b',
    currency        TEXT NOT NULL DEFAULT 'USD',
    native_enabled  INTEGER NOT NULL DEFAULT 1,
    custom_amounts  TEXT NOT NULL DEFAULT '[1,5,10,25]',
    min_amount      INTEGER NOT NULL DEFAULT 100,
    status          TEXT NOT NULL DEFAULT 'active',
    metadata_json   TEXT NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tips_creators_user ON tips_creators(user_id);
CREATE INDEX IF NOT EXISTS idx_tips_creators_status ON tips_creators(status);

CREATE TABLE IF NOT EXISTS tips_connectors (
    rowid           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id              TEXT PRIMARY KEY,
    creator_id      TEXT NOT NULL,
    connector_type  TEXT NOT NULL,
    label           TEXT,
    config_json     TEXT NOT NULL DEFAULT '{}',
    status          TEXT NOT NULL DEFAULT 'active',
    last_event_at   TIMESTAMPTZ,
    event_count     INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (creator_id) REFERENCES tips_creators(id) ON DELETE CASCADE,
    UNIQUE (creator_id, connector_type)
);
CREATE INDEX IF NOT EXISTS idx_tips_connectors_creator ON tips_connectors(creator_id);

CREATE TABLE IF NOT EXISTS tips_events (
    rowid           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id              TEXT PRIMARY KEY,
    creator_id      TEXT NOT NULL,
    connector_id    TEXT,
    source          TEXT NOT NULL,
    event_type      TEXT NOT NULL DEFAULT 'tip',
    sender          TEXT,
    amount_value    TEXT,
    amount_currency TEXT NOT NULL DEFAULT 'USD',
    amount_minor    INTEGER,
    message         TEXT,
    is_anonymous    INTEGER NOT NULL DEFAULT 0,
    visibility      TEXT NOT NULL DEFAULT 'public',
    external_id     TEXT,
    raw_json        TEXT,
    received_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (creator_id) REFERENCES tips_creators(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tips_events_creator ON tips_events(creator_id, received_at);
CREATE INDEX IF NOT EXISTS idx_tips_events_source ON tips_events(source, received_at);
CREATE INDEX IF NOT EXISTS idx_tips_events_external ON tips_events(source, external_id);

CREATE TABLE IF NOT EXISTS tips_webhook_tokens (
    rowid           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id              TEXT PRIMARY KEY,
    creator_id      TEXT NOT NULL,
    token           TEXT NOT NULL UNIQUE,
    label           TEXT,
    last_used_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (creator_id) REFERENCES tips_creators(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tips_wh_tokens_creator ON tips_webhook_tokens(creator_id);
CREATE INDEX IF NOT EXISTS idx_tips_wh_tokens_token ON tips_webhook_tokens(token);
