-- OpenVibe — community Phase 16 schema additions: paste version history
-- and discord relay audit trail. These mirror the SQLite schema added in
-- services/openvibe-community/server/db.js for the same milestone and are
-- safe to apply repeatedly via IF NOT EXISTS guards.

CREATE TABLE IF NOT EXISTS community_paste_versions (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    paste_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    title TEXT,
    body TEXT NOT NULL,
    language TEXT,
    edited_by_actor_type TEXT,
    edited_by_actor_id TEXT,
    change_summary TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (paste_id, version),
    FOREIGN KEY (paste_id) REFERENCES community_pastes(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_community_paste_versions_paste
    ON community_paste_versions(paste_id, version DESC);

CREATE TABLE IF NOT EXISTS community_relay_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rowid BIGINT GENERATED ALWAYS AS (id) STORED UNIQUE,
    relay_direction TEXT NOT NULL,
    outcome TEXT NOT NULL,
    relay_id TEXT,
    discord_channel_id TEXT,
    discord_message_id TEXT,
    openvibe_post_id TEXT,
    openvibe_thread_id TEXT,
    idempotency_key TEXT,
    error_message TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_community_relay_audit_dir
    ON community_relay_audit(relay_direction, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_community_relay_audit_outcome
    ON community_relay_audit(outcome, recorded_at DESC);
