-- OpenVibe — community voting: community_votes table and thread score columns.
-- Adds upvote/downvote tracking per thread and per user, plus denormalised
-- score/upvotes/downvotes/view_count/post_count columns on community_threads.
-- Safe to apply repeatedly via IF NOT EXISTS / ADD COLUMN IF NOT EXISTS guards.

CREATE TABLE IF NOT EXISTS community_votes (
    rowid       BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id          TEXT PRIMARY KEY,
    thread_id   TEXT NOT NULL,
    user_id     TEXT NOT NULL,
    direction   INTEGER NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(thread_id, user_id),
    FOREIGN KEY (thread_id) REFERENCES community_threads(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_community_votes_thread ON community_votes(thread_id);

ALTER TABLE community_threads ADD COLUMN IF NOT EXISTS score       INTEGER NOT NULL DEFAULT 0;
ALTER TABLE community_threads ADD COLUMN IF NOT EXISTS upvotes     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE community_threads ADD COLUMN IF NOT EXISTS downvotes   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE community_threads ADD COLUMN IF NOT EXISTS view_count  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE community_threads ADD COLUMN IF NOT EXISTS post_count  INTEGER NOT NULL DEFAULT 0;
