-- Phase 16 — first-class call participant lifecycle, stream-room bindings,
-- and durable per-owner audio integrations. Mirrors the additions in
-- services/openvibe-chat/server/db.js SCHEMA_SQL.

CREATE TABLE IF NOT EXISTS chat_call_participants (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    call_id TEXT NOT NULL,
    actor_type TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    role TEXT NOT NULL DEFAULT 'participant',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    PRIMARY KEY (call_id, actor_type, actor_id),
    FOREIGN KEY (call_id) REFERENCES chat_call_sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_call_parts_call ON chat_call_participants(call_id);
CREATE INDEX IF NOT EXISTS idx_chat_call_parts_actor ON chat_call_participants(actor_type, actor_id);

CREATE TABLE IF NOT EXISTS chat_stream_bindings (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    stream_ref_type TEXT NOT NULL,
    stream_ref_id TEXT NOT NULL,
    room_id TEXT NOT NULL,
    channel_id TEXT,
    tts_owner_type TEXT,
    tts_owner_id TEXT,
    audio_owner_type TEXT,
    audio_owner_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (stream_ref_type, stream_ref_id),
    FOREIGN KEY (room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_stream_bindings_room ON chat_stream_bindings(room_id);

CREATE TABLE IF NOT EXISTS chat_audio_integrations (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT PRIMARY KEY,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    label TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    config_json TEXT NOT NULL DEFAULT '{}',
    credential_ref TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_type, owner_id, provider, label)
);
CREATE INDEX IF NOT EXISTS idx_chat_audio_integrations_owner
    ON chat_audio_integrations(owner_type, owner_id);
